### ISSUE TITLE
mapfishapp - better progressbar

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1366]
google maps uses a css animated bar on top of the frame, it's actually pretty nice.

``` html
<div jstcache="107" role="progressbar" class="progress">
  <div class="progress-rect progress-rect-one">
    <span class="progress-rect-inner"></span>
  </div>
  <div class="progress-rect progress-rect-two">
    <span class="progress-rect-inner"></span>
  </div>
</div>
```

``` css
.progress{height:4px;overflow:hidden;position:absolute;top:0;-webkit-transform:translateZ(0);transform:translateZ(0);-webkit-transition:opacity 250ms linear;transition:opacity 250ms linear;width:100%}.progress-rect{-webkit-animation:none;animation:none;height:100%;position:absolute;-ms-transform-origin:top left;-webkit-transform-origin:top left;transform-origin:top left;width:100%}.progress-rect-inner{-webkit-animation:none;animation:none;background-color:#4285F4;display:inline-block;height:100%;position:absolute;width:100%}@keyframes rect-one-translate {0%{-webkit-transform:translateX(0px);transform:translateX(0px)}20%{-webkit-animation-timing-function:cubic-bezier(.5,0,.701732,.495819);animation-timing-function:cubic-bezier(.5,0,.701732,.495819);-webkit-transform:translateX(0px);transform:translateX(0px)}59.15%{-webkit-animation-timing-function:cubic-bezier(.302435,.381352,.55,.956352);animation-timing-function:cubic-bezier(.302435,.381352,.55,.956352);-webkit-transform:translateX(83.67142%);transform:translateX(83.67142%)}100%{-webkit-transform:translateX(200.611057%);transform:translateX(200.611057%)}}@keyframes rect-one-scale {0%{-webkit-transform:scaleX(.08);transform:scaleX(.08)}36.65%{-webkit-animation-timing-function:cubic-bezier(.334731,.124820,.785844,1);animation-timing-function:cubic-bezier(.334731,.124820,.785844,1);-webkit-transform:scaleX(.08);transform:scaleX(.08)}69.15%{-webkit-animation-timing-function:cubic-bezier(.06,.11,.6,1);animation-timing-function:cubic-bezier(.06,.11,.6,1);-webkit-transform:scaleX(.661479);transform:scaleX(.661479)}100%{-webkit-transform:scaleX(.08);transform:scaleX(.08)}}@keyframes rect-two-translate {0%{-webkit-animation-timing-function:cubic-bezier(.15,0,.515058,.409685);animation-timing-function:cubic-bezier(.15,0,.515058,.409685);-webkit-transform:translateX(0px);transform:translateX(0px)}25%{-webkit-animation-timing-function:cubic-bezier(.310330,.284058,.8,.733712);animation-timing-function:cubic-bezier(.310330,.284058,.8,.733712);-webkit-transform:translateX(37.651913%);transform:translateX(37.651913%)}48.35%{-webkit-animation-timing-function:cubic-bezier(.4,.627035,.6,.902026);animation-timing-function:cubic-bezier(.4,.627035,.6,.902026);-webkit-transform:translateX(84.386165%);transform:translateX(84.386165%)}100%{-webkit-transform:translateX(160.277782%);transform:translateX(160.277782%)}}@keyframes rect-two-scale {0%{-webkit-animation-timing-function:cubic-bezier(.205028,.057051,.576610,.453971);animation-timing-function:cubic-bezier(.205028,.057051,.576610,.453971);-webkit-transform:scaleX(.08);transform:scaleX(.08)}19.15%{-webkit-animation-timing-function:cubic-bezier(.152313,.196432,.648374,1.004315);animation-timing-function:cubic-bezier(.152313,.196432,.648374,1.004315);-webkit-transform:scaleX(.457104);transform:scaleX(.457104)}44.15%{-webkit-animation-timing-function:cubic-bezier(.257759,-0.003163,.211762,1.381790);animation-timing-function:cubic-bezier(.257759,-0.003163,.211762,1.381790);-webkit-transform:scaleX(.727960);transform:scaleX(.727960)}100%{-webkit-transform:scaleX(.08);transform:scaleX(.08)}}.progress-rect-one{-webkit-animation:rect-one-translate 2s infinite linear;animation:rect-one-translate 2s infinite linear;left:-145.166611%}.progress-rect-one>.progress-rect-inner{-webkit-animation:rect-one-scale 2s infinite linear;animation:rect-one-scale 2s infinite linear}.progress-rect-two{-webkit-animation:rect-two-translate 2s infinite linear;animation:rect-two-translate 2s infinite linear;left:-54.888891%;visibility:visible}.progress-rect-two>.progress-rect-inner{-webkit-animation:rect-two-scale 2s infinite linear;animation:rect-two-scale 2s infinite linear}
```
