### ISSUE TITLE
docker composition - needs a reverse proxy

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1475]
As discussed earlier, (in https://github.com/georchestra/georchestra/pull/1474#issuecomment-246480763) I think that:
- the docker-master branch should be updated in order to have `georchestra.mydomain.org` as the default frontend FQDN
- the composition should include some kind of reverse proxy (eg https://hub.docker.com/r/jwilder/nginx-proxy/) sitting in front of our security-proxy, something like eg:

``` yml
rp:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /path/to/certs:/etc/nginx/certs

proxy:
  image: georchestra/security-proxy:latest
  ports:
    - "8080:8080"
  volumes:
    - /etc/georchestra:/etc/georchestra
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - ...
  environment:
    - VIRTUAL_HOST=georchestra.mydomain.org
    - VIRTUAL_PROTO=https
    - XMX=1g
```
