### ISSUE TITLE
Remove wait-for-db scripts ?

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#1867]
Use docker healthchecks instead...

The following healthcheck has been configured to periodically check if PostgreSQL is ready using the `pg_isready` command. See the documentation for the `pg_isready` command [here](https://www.postgresql.org/docs/9.4/static/app-pg-isready.html).
```
healthcheck:
  test: ["CMD-SHELL", "pg_isready -U postgres"]
  interval: 30s
  timeout: 30s
  retries: 3
```
If the check is successful the container will be marked as `healthy`. Until then it will remain in an `unhealthy` state.
For more details about the healthcheck parameters `interval`, `timeout` and `retries` see the documentation [here](https://docs.docker.com/engine/reference/builder/#healthcheck).

Services that depend on PostgreSQL can then be configured with the `depends_on` parameter as follows:
```
depends_on:
  postgres-database:
    condition: service_healthy
```

from https://github.com/peter-evans/docker-compose-healthcheck#waiting-for-postgresql-to-be-healthy
