### ISSUE TITLE
[gh-actions] use cache action

### ISSUE THREAD

**Issue by landryb** [georchestra/georchestra#2979]
geoserver did this in geoserver/geoserver#4008 (cf https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) and that might be useful to waste less resources:
```
    - name: Maven repository caching
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B clean install -T2 -Prelease --file src/pom.xml
    - name: Remove SNAPSHOT jars from repository
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
```
