### ISSUE TITLE
actions - add ability to skip CI

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#2988]
```
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
```
