### ISSUE TITLE
actions - prevent double build on release

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/georchestra#3035]
We currently build apps 2 times when a release is made:
![Capture du 2020-04-15 15-30-24](https://user-images.githubusercontent.com/265319/79342951-1671c780-7f2e-11ea-8681-cb54e2e84817.png)

One because of the release commit and an other one because of the github `release` event is fired.
I think we should try on a toy project the following:
```yaml
on:
  push:
    tags:
    paths:
      - "commons/**"
      - "console/**"
  pull_request:
    paths:
      - "commons/**"
      - "console/**"
```
rather than:
```yaml
on:
  push:
    paths:
      - "commons/**"
      - "console/**"
  pull_request:
    paths:
      - "commons/**"
      - "console/**"
  release:
    types: [published]
```
