### ISSUE TITLE
datafeeder - logs configuration 

### ISSUE THREAD

**Issue by jeanpommier** [georchestra/georchestra#3892]
How can I configure the logs for the datafeeder backend ?

**Comment by landryb** [comment]
after looking, application.yml is where it's configured, *but* its not in the datadir by default, and we dont know if it'd be read. It's bundled in the datafeeder jar..

**Comment by jeanpommier** [comment]
[Answering to myself]

Since this is a spring boot app, this is supposed to be possible either in the .properties file, or using env. vars.

I couldn't make it work using the datafeeder.properties file in the datadir, but environment variables seem to work, e.g. setting LOGGING_LEVEL_ORG_GEORCHESTRA_DATAFEEDER to DEBUG

see https://docs.spring.io/spring-boot/docs/2.1.13.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-levels

**Comment by fvanderbiest** [comment]
Might make sense to have this var exposed by default in https://github.com/georchestra/docker/blob/73655f487a4d2d9f1ac58a6ffc15b945addd2099/docker-compose.yml#L176-L182 ...

**Comment by fvanderbiest** [comment]
Just tested ATM.
Seems I cannot limit log level to WARN with the following:
```  
  datafeeder:
    image: georchestra/datafeeder:latest
    privileged: true
    volumes:
      - ./config:/etc/georchestra
      - datafeeder_uploads:/tmp/datafeeder
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
      - LOGGING_LEVEL_ORG_GEORCHESTRA_DATAFEEDER=WARN
   ```
(BTW, removing option MaxPermSize=128m; support was removed in 8.0)
